spring:
  main:
    banner-mode: off

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  datasource:
    url: "jdbc:postgresql://localhost:5432/noteapp"
    driver-class-name: org.postgresql.Driver
    username: safonov

  liquibase:
    enabled: false
    default-schema: "noteapp"
    parameters:
      db_schema: "noteapp"
    change-log: "classpath:db.changelog/db.changelog-master.yml"

server:
  port: 8080

odata:
  authentication:
    header:
      name: WWW-Authenticate
      value: Basic <token>