CREATE TABLE "${db_schema}".USER(
    ID BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(64) NOT NULL UNIQUE,
    PASSWORD VARCHAR(64) NOT NULL
);
COMMENT ON TABLE "${db_schema}".USER IS 'Хранит пользователей приложения';

CREATE TABLE "${db_schema}".NOTE(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    CONTENT VARCHAR(2048) NOT NULL,
    AUTHOR_ID BIGSERIAL NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES "${db_schema}".USER(ID)
);
COMMENT ON TABLE "${db_schema}".USER IS 'Хранит записи пользователей';

CREATE TABLE "${db_schema}".PERMISSION(
    ID BIGSERIAL PRIMARY KEY,
    NOTE_ID BIGSERIAL NOT NULL,
    USER_ID BIGSERIAL NOT NULL,
    PERMIT_ALL BOOLEAN NOT NULL DEFAULT FALSE,
    READ BOOLEAN NOT NULL DEFAULT FALSE,
    WRITE BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (NOTE_ID) REFERENCES "${db_schema}".NOTE(ID),
    FOREIGN KEY (USER_ID) REFERENCES "${db_schema}".USER(ID)
);
COMMENT ON TABLE "${db_schema}".USER IS 'Хранит права доступа пользователей к записям';